### ISSUE TITLE
Netflix nad gitlab is down

### ISSUE THREAD

**Issue by krystofex** [filiptronicek/BRUH#18]
![image](https://user-images.githubusercontent.com/48121710/131734982-9c79aafe-1550-4681-863a-6b07479b5c22.png)
![image](https://user-images.githubusercontent.com/48121710/131735016-45104aa8-8e82-40e0-8354-4eb0e268f4bf.png)

**Comment by filiptronicek** [comment]
Fixed in fcf1b3350c6ce6bb72140ac56e04a11f7df7b509
